-- Generated preview from schema_definition.csv. The notebook executes equivalent DDL.

CREATE TABLE IF NOT EXISTS `silver`.`slv_document_s3_file_metadata` (
  `s3_file_metadata_id` STRING NOT NULL,
  `original_filename` STRING NOT NULL,
  `file_name` STRING,
  `s3_bucket` STRING NOT NULL,
  `object_key` STRING NOT NULL,
  `upload_timestamp` TIMESTAMP NOT NULL,
  `file_size` STRING,
  `content_type` STRING NOT NULL,
  `document_name` STRING,
  `document_type` STRING,
  `expiry_date` DATE,
  `last_updated` DATE,
  `next_review_date` DATE,
  `service_type` STRING,
  `home_id` STRING,
  `start_date` DATE,
  `expiry_data` DATE,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_ipa_ipa` (
  `ipa_id` STRING NOT NULL,
  `offer_id` STRING NOT NULL,
  `referral_id` STRING NOT NULL,
  `child_full_name` STRING,
  `child_known_as` STRING,
  `child_date_of_birth` DATE,
  `child_age_years` INT,
  `child_gender` STRING,
  `child_ethnicity` STRING,
  `child_preferred_language` STRING,
  `child_religion` STRING,
  `child_legal_status` STRING,
  `child_reference_number` STRING,
  `child_support_needs` STRING,
  `child_support_needs_other_text` STRING,
  `la_name` STRING,
  `la_addr_line1` STRING,
  `la_addr_line2` STRING,
  `la_addr_county` STRING,
  `la_addr_town` STRING,
  `la_addr_postcode` STRING,
  `la_phone` STRING,
  `la_email` STRING,
  `provider_name` STRING,
  `provider_addr_line1` STRING,
  `provider_addr_town` STRING,
  `provider_addr_postcode` STRING,
  `provider_phone` STRING,
  `provider_email` STRING,
  `provider_company_registration_number` STRING,
  `placement_framework_or_spot` STRING,
  `placement_service_type` STRING,
  `placement_category` STRING,
  `placement_admission_date` DATE,
  `placement_type` STRING,
  `placement_type_other_text` STRING,
  `placement_needs_summary` STRING,
  `home_name` STRING,
  `home_addr_line1` STRING,
  `home_addr_town` STRING,
  `home_addr_postcode` STRING,
  `home_phone` STRING,
  `home_email` STRING,
  `registered_manager_name` STRING,
  `registered_manager_phone` STRING,
  `registered_manager_email` STRING,
  `registered_manager_registration_number` STRING,
  `registered_manager_email_address` STRING,
  `provider_urn` STRING,
  `education_included_with_referral` BOOLEAN,
  `education_provision_name` STRING,
  `education_addr_line1` STRING,
  `education_addr_town` STRING,
  `education_addr_postcode` STRING,
  `education_location` STRING,
  `education_length_weeks` INT,
  `education_provision_cost` DECIMAL(19,2),
  `expected_destination_after_placement` STRING,
  `expected_destination_other_text` STRING,
  `outcomes_of_placement` STRING,
  `foster_enabled` BOOLEAN,
  `foster_primary_full_name` STRING,
  `foster_primary_age_years` INT,
  `foster_primary_language_spoken` STRING,
  `foster_primary_gender` STRING,
  `foster_primary_ethnicity` STRING,
  `foster_primary_religion` STRING,
  `foster_primary_phone` STRING,
  `foster_primary_email` STRING,
  `foster_primary_approval_date` DATE,
  `foster_primary_approval_details` STRING,
  `foster_additional_exists` BOOLEAN,
  `foster_additional_full_name` STRING,
  `foster_additional_age_years` INT,
  `foster_additional_language_spoken` STRING,
  `foster_additional_gender` STRING,
  `foster_additional_ethnicity` STRING,
  `foster_additional_religion` STRING,
  `foster_additional_phone` STRING,
  `foster_additional_email` STRING,
  `foster_additional_approval_date` DATE,
  `foster_additional_approval_details` STRING,
  `foster_home_addr_line1` STRING,
  `foster_home_addr_town` STRING,
  `foster_home_addr_postcode` STRING,
  `foster_home_has_pets` BOOLEAN,
  `foster_transport_can_provide_for_school` STRING,
  `foster_vehicle_details` STRING,
  `foster_safeguarding_reviewed` BOOLEAN,
  `social_worker_full_name` STRING,
  `social_worker_phone` STRING,
  `social_worker_email` STRING,
  `health_contact_full_name` STRING,
  `health_contact_organisation_name` STRING,
  `health_contact_phone` STRING,
  `health_contact_email` STRING,
  `advocacy_team_name` STRING,
  `advocacy_team_phone` STRING,
  `advocacy_team_email` STRING,
  `independent_review_officer_full_name` STRING,
  `independent_review_officer_phone` STRING,
  `independent_review_officer_email` STRING,
  `costs_total_weekly_fee` DECIMAL(12,2),
  `costs_total_core_costs_weekly_fee` DECIMAL(12,2),
  `core_cost_weekly_fee` DECIMAL(12,2),
  `payment_method` STRING,
  `invoice_recipient_name` STRING,
  `invoice_recipient_team` STRING,
  `invoice_recipient_email` STRING,
  `invoice_addr_line1` STRING,
  `invoice_addr_line2` STRING,
  `invoice_addr_county` STRING,
  `invoice_addr_town` STRING,
  `invoice_addr_postcode` STRING,
  `schedule_contact_name` STRING,
  `schedule_contact_phone` STRING,
  `schedule_contact_email` STRING,
  `schedule_addr_line1` STRING,
  `schedule_addr_line2` STRING,
  `schedule_addr_county` STRING,
  `schedule_addr_town` STRING,
  `schedule_addr_postcode` STRING,
  `schedule_do_not_send_invoices_note` STRING,
  `created_datetime` TIMESTAMP NOT NULL,
  `updated_datetime` TIMESTAMP,
  `provider_addr_line2` STRING,
  `provider_addr_county` STRING,
  `home_addr_line2` STRING,
  `home_addr_county` STRING,
  `education_addr_line2` STRING,
  `education_addr_county` STRING,
  `foster_home_addr_line2` STRING,
  `foster_home_addr_county` STRING,
  `foster_home_pets_details` STRING,
  `foster_transport_for_school_details` STRING,
  `foster_transport_can_provide_for_family` STRING,
  `foster_transport_can_provide_for_family_details` STRING,
  `created_by` STRING,
  `updated_by` STRING,
  `status` STRING,
  `signed_by_local_authority` BOOLEAN NOT NULL,
  `signed_datetime_for_local_authority` TIMESTAMP,
  `signed_by_provider_name` STRING,
  `signed_datetime_for_provider` TIMESTAMP,
  `signed_by_local_authority_name` STRING,
  `can_sign_name` STRING,
  `can_sign_date` TIMESTAMP,
  `can_sign` BOOLEAN NOT NULL,
  `closed` BOOLEAN NOT NULL,
  `closed_datetime` TIMESTAMP,
  `signed_by_provider` BOOLEAN NOT NULL,
  `provider_id` STRING,
  `child_age_months` INT,
  `invoice_recipient_phone` STRING,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_ipa_ipa_additional_fee` (
  `additional_fee_id` STRING NOT NULL,
  `ipa_id` STRING NOT NULL,
  `title` STRING NOT NULL,
  `fee_type` STRING NOT NULL,
  `one_off_fee` DECIMAL(19,2),
  `total` DECIMAL(19,2),
  `review_date` DATE,
  `end_date` DATE,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP,
  `hours_per_week` DECIMAL(19,2),
  `weekly_total` DECIMAL(19,2),
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_ipa_ipa_child` (
  `ipa_child_id` STRING NOT NULL,
  `ipa_id` STRING NOT NULL,
  `child_full_name` STRING NOT NULL,
  `child_known_as` STRING,
  `child_date_of_birth` DATE,
  `child_age_years` INT NOT NULL,
  `child_gender` STRING,
  `child_ethnicity` STRING,
  `child_preferred_language` STRING,
  `child_religion` STRING,
  `child_legal_status` STRING NOT NULL,
  `child_reference_number` STRING,
  `child_support_needs_other_text` STRING,
  `child_support_needs` STRING,
  `expected_destination_after_placement` STRING,
  `expected_destination_other_text` STRING,
  `child_age_months` INT,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_ipa_ipa_document` (
  `ipa_document_id` STRING NOT NULL,
  `ipa_id` STRING NOT NULL,
  `s3_file_metadata_id` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_offer_additional_fee` (
  `additional_fee_id` STRING NOT NULL,
  `offer_id` STRING NOT NULL,
  `fee_code` STRING,
  `number_of_hours` DECIMAL(6,1) NOT NULL,
  `other_fee_title` STRING,
  `fee_frequency` STRING NOT NULL,
  `rate` DECIMAL(6,2) NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_offer_foster_carer` (
  `foster_carer_id` STRING NOT NULL,
  `offer_id` STRING NOT NULL,
  `is_primary_carer` BOOLEAN NOT NULL,
  `full_name` STRING NOT NULL,
  `age` INT NOT NULL,
  `language_code` STRING NOT NULL,
  `language_other` STRING,
  `gender_code` STRING NOT NULL,
  `gender_other` STRING,
  `ethnicity_code` STRING NOT NULL,
  `ethnicity_other` STRING,
  `religion_code` STRING NOT NULL,
  `religion_other` STRING,
  `phone_number` STRING NOT NULL,
  `email_address` STRING NOT NULL,
  `date_of_approval` TIMESTAMP NOT NULL,
  `approval_details` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_offer_foster_home` (
  `foster_home_id` STRING NOT NULL,
  `offer_id` STRING NOT NULL,
  `address_line1` STRING NOT NULL,
  `address_line2` STRING,
  `town_or_city` STRING NOT NULL,
  `county` STRING,
  `postcode` STRING NOT NULL,
  `has_pets` BOOLEAN NOT NULL,
  `pets_details` STRING,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_offer_foster_transport` (
  `foster_transport_id` STRING NOT NULL,
  `offer_id` STRING NOT NULL,
  `school_transport_provision` STRING NOT NULL,
  `school_transport_details` STRING,
  `family_transport_provision` STRING NOT NULL,
  `family_transport_details` STRING,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_offer_offer` (
  `offer_id` STRING NOT NULL,
  `referral_provider_id` STRING NOT NULL,
  `offer_status` STRING NOT NULL,
  `provider_home_id` STRING NOT NULL,
  `id_number` STRING NOT NULL,
  `category` INT,
  `estimated_start_date` DATE,
  `core_weekly_fee` DECIMAL(6,2),
  `includes_education` BOOLEAN,
  `education_weekly_fee` DECIMAL(6,2),
  `child_summary_needs` STRING,
  `offer_date` TIMESTAMP,
  `last_modified_date` TIMESTAMP,
  `decline_code` STRING,
  `decline_reason` STRING,
  `can_edit_offer` BOOLEAN,
  `withdraw_reason` STRING,
  `withdraw_code` STRING,
  `offer_type` STRING,
  `category_code` STRING,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_offer_offer_document` (
  `s3_file_metadata_id` STRING NOT NULL,
  `offer_id` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_offer_offer_updates` (
  `offer_update_id` STRING NOT NULL,
  `offer_id` STRING,
  `offer_updates_requested` BOOLEAN,
  `message_id` STRING,
  `offer_updates_requested_at` TIMESTAMP,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_offer_offer_view_history` (
  `offer_view_id` STRING NOT NULL,
  `offer_id` STRING NOT NULL,
  `offer_viewed_by` STRING NOT NULL,
  `offer_viewed_at` TIMESTAMP,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_offer_supervising_social_worker` (
  `social_worker_id` STRING NOT NULL,
  `offer_id` STRING NOT NULL,
  `full_name` STRING NOT NULL,
  `phone_number` STRING NOT NULL,
  `email_address` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_ageband` (
  `age_band_id` INT NOT NULL,
  `age_band_label` STRING NOT NULL,
  `start_age` INT,
  `up_to_age` INT,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_form_submissions` (
  `id` STRING NOT NULL,
  `cognito_id` STRING NOT NULL,
  `file_name` STRING NOT NULL,
  `provider_name` STRING NOT NULL,
  `json_data` STRING NOT NULL,
  `status` STRING NOT NULL,
  `submission_date` TIMESTAMP NOT NULL,
  `reviewed_by` STRING,
  `review_date` TIMESTAMP,
  `review_comments` STRING,
  `last_modified_date` TIMESTAMP,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_fost_category_age_band` (
  `id` STRING NOT NULL,
  `provider_id` STRING NOT NULL,
  `age_band_id` INT NOT NULL,
  `framework_category_id` INT NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_holding_company` (
  `holding_company_id` STRING NOT NULL,
  `company_name` STRING NOT NULL,
  `address_line_1` STRING NOT NULL,
  `address_line_2` STRING,
  `town_city` STRING,
  `county` STRING,
  `postcode` STRING NOT NULL,
  `country` STRING,
  `company_phone_number` STRING NOT NULL,
  `company_email_address` STRING NOT NULL,
  `contact_person_name` STRING NOT NULL,
  `contact_person_phone_number` STRING,
  `contact_person_email_address` STRING,
  `companies_house_details` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_provider` (
  `provider_id` STRING NOT NULL,
  `holding_company_id` STRING NOT NULL,
  `provider_name` STRING NOT NULL,
  `address_line_1` STRING NOT NULL,
  `address_line_2` STRING,
  `town_city` STRING,
  `county` STRING,
  `postcode` STRING NOT NULL,
  `country` STRING,
  `provider_status` STRING NOT NULL,
  `provider_email_address` STRING,
  `provider_phone_number` STRING,
  `last_regulating_body_inspection_date` DATE,
  `regulatory_body_registration_reference` STRING,
  `inspection_outcome_rating` STRING,
  `responsible_individual_name` STRING,
  `responsible_individual_contact_number` STRING,
  `responsible_individual_email_address` STRING,
  `registrant_name` STRING,
  `registrant_role` STRING,
  `registrant_email_address` STRING,
  `registrant_contact_number` STRING,
  `sic_codes` ARRAY<STRING> NOT NULL,
  `companies_house_registration_reference` STRING,
  `national_contract_external_link` STRING,
  `created_by` STRING NOT NULL,
  `modified_by` STRING,
  `created_timestamp` TIMESTAMP NOT NULL,
  `modified_timestamp` TIMESTAMP,
  `regulatory_body_name` STRING,
  `is_fostering_spot` BOOLEAN,
  `qa_flag` BOOLEAN,
  `qa_flag_fostering_spot` BOOLEAN,
  `qa_flag_sup_acc` BOOLEAN,
  `qa_flag_resi` BOOLEAN,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_provider_document` (
  `s3_file_metadata_id` STRING NOT NULL,
  `s3_file_metadata_id` STRING NOT NULL,
  `provider_id` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_provider_education_provision` (
  `provider_education_provision_id` STRING NOT NULL,
  `provider_id` STRING NOT NULL,
  `provider_home_id` STRING NOT NULL,
  `education_privision_name` STRING,
  `education_provision_type` STRING NOT NULL,
  `address_line_1` STRING NOT NULL,
  `address_line_2` STRING,
  `town_city` STRING,
  `county` STRING,
  `postcode` STRING NOT NULL,
  `country` STRING,
  `contact_name` STRING NOT NULL,
  `contact_number` STRING,
  `contact_email_address` STRING,
  `last_regulating_body_inspection_date` DATE,
  `regulatory_body_registration_reference` STRING,
  `inspection_outcome_rating` STRING,
  `created_by` STRING NOT NULL,
  `modified_by` STRING,
  `created_timestamp` TIMESTAMP NOT NULL,
  `modified_timestamp` TIMESTAMP,
  `regulatory_body_name` STRING,
  `dfe_registration_number` STRING,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_provider_framework` (
  `provider_framework_id` BIGINT NOT NULL,
  `provider_id` STRING NOT NULL,
  `framework_code` STRING NOT NULL,
  `qa_flag` BOOLEAN,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_provider_home` (
  `provider_home_id` STRING NOT NULL,
  `provider_id` STRING NOT NULL,
  `service_type` STRING NOT NULL,
  `home_name` STRING NOT NULL,
  `address_line_1` STRING NOT NULL,
  `address_line_2` STRING,
  `town_city` STRING,
  `county` STRING,
  `postcode` STRING NOT NULL,
  `country` STRING,
  `home_contact_number` STRING,
  `home_email_address` STRING,
  `registered_manager_name` STRING,
  `registered_manager_contact_number` STRING,
  `registered_manager_email_address` STRING,
  `number_of_registered_beds` INT,
  `regulatory_body_registration_reference` STRING,
  `last_regulating_body_inspection_date` DATE,
  `inspection_outcome_rating` STRING,
  `created_by` STRING NOT NULL,
  `modified_by` STRING,
  `created_timestamp` TIMESTAMP NOT NULL,
  `modified_timestamp` TIMESTAMP,
  `is_spot` BOOLEAN NOT NULL,
  `responsible_individual_name` STRING,
  `responsible_individual_role` STRING,
  `responsible_individual_email_address` STRING,
  `regulatory_body_name` STRING,
  `regulatory_body_registration_date` DATE,
  `age_band_id` INT,
  `qa_flag` BOOLEAN,
  `qa_flag_spot` BOOLEAN,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_provider_home_age` (
  `provider_home_age_id` BIGINT NOT NULL,
  `provider_home_id` STRING NOT NULL,
  `min_age` INT,
  `max_age` INT,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_provider_home_category` (
  `provider_home_category_id` BIGINT NOT NULL,
  `framework_category_id` INT NOT NULL,
  `provider_home_id` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_provider_home_gender` (
  `provider_home_gender_id` BIGINT NOT NULL,
  `provider_home_id` STRING NOT NULL,
  `supported_gender` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_provider_home_ofsted_category` (
  `provider_home_ofsted_category_id` INT NOT NULL,
  `ofsted_category` STRING,
  `provider_home_id` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_provider_home_spot_category` (
  `provider_home_spot_category_id` BIGINT NOT NULL,
  `provider_home_id` STRING NOT NULL,
  `spot_category_code` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_provider_submission_documents` (
  `document_id` STRING NOT NULL,
  `submission_id` STRING NOT NULL,
  `s3_file_metadata_id` STRING NOT NULL,
  `s3_file_metadata_id` STRING NOT NULL,
  `document_name` STRING NOT NULL,
  `document_type` STRING NOT NULL,
  `expiry_date` DATE,
  `last_updated` DATE,
  `next_review_date` DATE,
  `service_type` STRING,
  `home_id` STRING,
  `start_date` DATE,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_refdata_refdata` (
  `ref_code` STRING NOT NULL,
  `ref_type` STRING NOT NULL,
  `ref_value_1` STRING NOT NULL,
  `ref_value_2` STRING,
  `is_active` BOOLEAN NOT NULL,
  `valid_from` DATE NOT NULL,
  `valid_to` DATE,
  `created_by` STRING NOT NULL,
  `modified_by` STRING,
  `created_timestamp` TIMESTAMP NOT NULL,
  `modified_timestamp` TIMESTAMP,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_la_reset_counter_history` (
  `reset_counter_id` STRING NOT NULL,
  `referral_provider_id` STRING NOT NULL,
  `is_counter_reset` BOOLEAN NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_person` (
  `person_id` STRING NOT NULL,
  `initials` STRING NOT NULL,
  `age_value` INT NOT NULL,
  `age_date_unit` STRING NOT NULL,
  `has_restrictions` BOOLEAN NOT NULL,
  `restriction_details` STRING,
  `source_reference_id` STRING NOT NULL,
  `gender` STRING NOT NULL,
  `gender_other` STRING,
  `ethnicity` STRING NOT NULL,
  `ethnicity_other` STRING,
  `religion` STRING NOT NULL,
  `religion_other` STRING,
  `preferred_language` STRING NOT NULL,
  `preferred_language_other` STRING,
  `referral_id` STRING NOT NULL,
  `child_index` INT NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_person_aud` (
  `id` STRING NOT NULL,
  `rev` INT NOT NULL,
  `revtype` BIGINT,
  `person_id` STRING,
  `initials` STRING,
  `age_value` INT,
  `age_date_unit` STRING,
  `has_restrictions` BOOLEAN,
  `restriction_details` STRING,
  `source_reference_id` STRING,
  `gender_code` STRING,
  `gender_other` STRING,
  `ethnicity_code` STRING,
  `ethnicity_other` STRING,
  `religion_code` STRING,
  `religion_other` STRING,
  `preferred_language_code` STRING,
  `preferred_language_other` STRING,
  `referral_id` STRING,
  `initials_mod` BOOLEAN,
  `age_value_mod` BOOLEAN,
  `age_date_unit_mod` BOOLEAN,
  `has_restrictions_mod` BOOLEAN,
  `restriction_details_mod` BOOLEAN,
  `source_reference_id_mod` BOOLEAN,
  `gender_code_mod` BOOLEAN,
  `gender_other_mod` BOOLEAN,
  `ethnicity_code_mod` BOOLEAN,
  `ethnicity_other_mod` BOOLEAN,
  `religion_code_mod` BOOLEAN,
  `religion_other_mod` BOOLEAN,
  `preferred_language_code_mod` BOOLEAN,
  `preferred_language_other_mod` BOOLEAN,
  `referral_id_mod` BOOLEAN,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral` (
  `referral_id` STRING NOT NULL,
  `placement_type_code` STRING NOT NULL,
  `required_start_date` DATE NOT NULL,
  `response_required_by_date` DATE NOT NULL,
  `is_sibling_placement` BOOLEAN NOT NULL,
  `sibling_count` INT NOT NULL,
  `is_parent_child_placement` BOOLEAN NOT NULL,
  `has_location_preferrence` BOOLEAN NOT NULL,
  `location_preference_details` STRING,
  `has_location_restriction` BOOLEAN NOT NULL,
  `location_restriction_details` STRING,
  `additional_information` STRING,
  `created_by` STRING NOT NULL,
  `modified_by` STRING,
  `created_timestamp` TIMESTAMP NOT NULL,
  `modified_timestamp` TIMESTAMP,
  `is_spot` BOOLEAN NOT NULL,
  `status` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_aud` (
  `id` STRING NOT NULL,
  `rev` INT NOT NULL,
  `revtype` BIGINT,
  `referral_id` STRING,
  `placement_type_code` STRING,
  `required_start_date` DATE,
  `response_required_by_date` DATE,
  `has_location_preferrence` BOOLEAN,
  `location_preference_details` STRING,
  `has_location_restriction` BOOLEAN,
  `location_restriction_details` STRING,
  `additional_information` STRING,
  `created_timestamp` TIMESTAMP,
  `modified_timestamp` TIMESTAMP,
  `created_by` STRING,
  `modified_by` STRING,
  `status` STRING,
  `placement_type_code_mod` BOOLEAN,
  `required_start_date_mod` BOOLEAN,
  `response_required_by_date_mod` BOOLEAN,
  `has_location_preference_mod` BOOLEAN,
  `location_preference_details_mod` BOOLEAN,
  `has_location_restriction_mod` BOOLEAN,
  `location_restriction_details_mod` BOOLEAN,
  `additional_information_mod` BOOLEAN,
  `created_timestamp_mod` BOOLEAN,
  `modified_timestamp_mod` BOOLEAN,
  `created_by_mod` BOOLEAN,
  `modified_by_mod` BOOLEAN,
  `status_mod` BOOLEAN,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_category` (
  `referral_id` STRING NOT NULL,
  `framework_category_id` INT NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_category_aud` (
  `id` STRING NOT NULL,
  `rev` INT NOT NULL,
  `revtype` BIGINT,
  `referral_id` STRING,
  `framework_category_id` INT,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_document` (
  `s3_file_metadata_id` STRING NOT NULL,
  `referral_id` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_document_aud` (
  `id` STRING NOT NULL,
  `rev` INT NOT NULL,
  `revtype` BIGINT,
  `s3_file_metadata_id` STRING,
  `referral_id` STRING,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_event_log` (
  `event_id` BIGINT NOT NULL,
  `referral_id` STRING NOT NULL,
  `event_type` STRING NOT NULL,
  `event_message` STRING NOT NULL,
  `event_username` STRING NOT NULL,
  `event_timestamp` TIMESTAMP NOT NULL,
  `sequence_number` INT NOT NULL,
  `created_by` STRING NOT NULL,
  `created_timestamp` TIMESTAMP NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_local_authority` (
  `referral_local_authority_id` STRING NOT NULL,
  `referral_id` STRING NOT NULL,
  `local_authority_id` STRING NOT NULL,
  `is_referral_owner` STRING NOT NULL,
  `created_timestamp` TIMESTAMP,
  `modified_timestamp` TIMESTAMP,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_provider` (
  `referral_provider_id` STRING NOT NULL,
  `referral_id` STRING NOT NULL,
  `provider_id` STRING NOT NULL,
  `is_excluded` BOOLEAN NOT NULL,
  `is_declined` BOOLEAN NOT NULL,
  `created_by` STRING NOT NULL,
  `modified_by` STRING,
  `created_timestamp` TIMESTAMP NOT NULL,
  `modified_timestamp` TIMESTAMP,
  `is_cancelled` BOOLEAN NOT NULL,
  `is_closed` BOOLEAN NOT NULL,
  `is_spot` BOOLEAN NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_provider_cancel_reason` (
  `cancel_reason_id` BIGINT NOT NULL,
  `cancel_reason_code` STRING NOT NULL,
  `cancel_reason_other_text` STRING,
  `created_by` STRING NOT NULL,
  `created_timestamp` TIMESTAMP NOT NULL,
  `referral_provider_id` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_provider_decline_reason` (
  `decline_reason_id` BIGINT NOT NULL,
  `decline_reason_code` STRING NOT NULL,
  `decline_reason_other_text` STRING,
  `created_by` STRING NOT NULL,
  `created_timestamp` TIMESTAMP NOT NULL,
  `referral_provider_id` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_provider_message` (
  `message_id` STRING NOT NULL,
  `message_text` STRING NOT NULL,
  `created_timestamp` TIMESTAMP NOT NULL,
  `created_by` STRING NOT NULL,
  `referral_provider_id` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_provider_message_attachement` (
  `message_attachement_id` STRING NOT NULL,
  `message_id` STRING NOT NULL,
  `s3_file_metadata_id` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_provider_message_status` (
  `message_status_id` STRING NOT NULL,
  `message_id` STRING NOT NULL,
  `message_read_by` STRING NOT NULL,
  `message_read_timestamp` TIMESTAMP NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_provider_reopen_history` (
  `referral_provider_reopen_history_id` BIGINT NOT NULL,
  `referral_provider_id` STRING NOT NULL,
  `referral_reopen_timestamp` TIMESTAMP NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_save` (
  `referral_save_id` STRING NOT NULL,
  `referral_id` STRING NOT NULL,
  `saved_by` STRING NOT NULL,
  `saved_timestamp` TIMESTAMP NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_spot_category` (
  `referral_spot_category_id` BIGINT NOT NULL,
  `referral_id` STRING NOT NULL,
  `spot_category_code` STRING NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_updates_history` (
  `update_id` STRING NOT NULL,
  `referral_provider_id` STRING,
  `referral_update_timestamp` TIMESTAMP,
  `isviewedbyprovider` BOOLEAN,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_referral_referral_view_history` (
  `referral_view_id` STRING NOT NULL,
  `referral_id` STRING NOT NULL,
  `viewed_by` STRING NOT NULL,
  `viewed_timestamp` TIMESTAMP NOT NULL,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_wmpp_users_roles` (
  `role_id` STRING NOT NULL,
  `role_name` STRING NOT NULL,
  `description` STRING,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;

CREATE TABLE IF NOT EXISTS `silver`.`slv_wmpp_users_users` (
  `user_id` STRING NOT NULL,
  `firstname` STRING NOT NULL,
  `lastname` STRING NOT NULL,
  `email` STRING NOT NULL,
  `user_group` STRING NOT NULL,
  `role_id` STRING NOT NULL,
  `provider_id` STRING,
  `local_authority_id` STRING,
  `personal_email` STRING,
  `local_authority_team` STRING,
  `title` STRING,
  `job_tile` STRING,
  `office_phone` STRING,
  `mobile_phone` STRING,
  `service_type` STRING,
  `_record_source` STRING,
  `_source_table` STRING,
  `_source_file_path` STRING,
  `_export_date` DATE,
  `_silver_run_id` STRING,
  `_silver_load_ts` TIMESTAMP
) USING DELTA;
