table fact_referral_category
	lineageTag: a6e9720a-574a-4988-b878-eb90c29f2e15

	column referral_id
		dataType: string
		lineageTag: 6e24ae2a-aedf-4101-8918-2aec8a66132d
		summarizeBy: none
		sourceColumn: referral_id

		annotation SummarizationSetBy = Automatic

	column framework_category_id
		dataType: string
		lineageTag: 9ca965d9-dc15-4ec6-bbf2-2e16488368c2
		summarizeBy: none
		sourceColumn: framework_category_id

		annotation SummarizationSetBy = Automatic

	column export_date
		dataType: string
		lineageTag: 6bbc3f3f-d364-4f89-b253-8c33c665f942
		summarizeBy: none
		sourceColumn: export_date

		annotation SummarizationSetBy = Automatic

	column referral_sk
		dataType: string
		lineageTag: ac804870-1987-49b1-aea9-4210a71fadb9
		summarizeBy: none
		sourceColumn: referral_sk

		annotation SummarizationSetBy = Automatic

	column category_sk
		dataType: int64
		formatString: 0
		lineageTag: a6905b57-c04f-45a0-864d-bd09f801fa47
		summarizeBy: sum
		sourceColumn: category_sk

		annotation SummarizationSetBy = Automatic

	column _ingestion_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 817deb42-5ba8-4fe5-b773-5cbc988b28bf
		summarizeBy: none
		sourceColumn: _ingestion_timestamp

		variation Variation
			isDefault
			relationship: 6231b704-fab8-4534-b1d4-604ccc29104e
			defaultHierarchy: LocalDateTable_617d99c0-18ec-4835-8ac6-48f2871af54d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _source_file
		dataType: string
		lineageTag: 655eb6ea-2e57-48e0-8725-7843665a3cc1
		summarizeBy: none
		sourceColumn: _source_file

		annotation SummarizationSetBy = Automatic

	column _ingestion_id
		dataType: string
		lineageTag: f7caf56c-4fc2-413a-ac41-c774e0dcce44
		summarizeBy: none
		sourceColumn: _ingestion_id

		annotation SummarizationSetBy = Automatic

	partition fact_referral_category = m
		mode: import
		source =
				let
				    Source = #"bronze referral_category",
				    #"Merged Queries" = Table.NestedJoin(Source, {"referral_id"}, dim_referral, {"referral_id"}, "dim_referral", JoinKind.LeftOuter),
				    #"Expanded dim_referral" = Table.ExpandTableColumn(#"Merged Queries", "dim_referral", {"referral_sk"}, {"referral_sk"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded dim_referral", {"framework_category_id"}, dim_category, {"framework_category_id"}, "dim_category", JoinKind.LeftOuter),
				    #"Expanded dim_category" = Table.ExpandTableColumn(#"Merged Queries1", "dim_category", {"category_sk"}, {"category_sk"})
				in
				    #"Expanded dim_category"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
