table 'Fact Referral Snapshot'
	lineageTag: a0f03b9a-16bc-41c7-8d18-46b24226ab02

	column SnapshotDate
		dataType: dateTime
		formatString: dd mmmm yyyy
		sourceProviderType: date
		lineageTag: 317021bf-acec-4ad8-82a1-8410681c7121
		summarizeBy: none
		sourceColumn: SnapshotDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ReferralID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c5635d76-55e7-4621-9736-331535a7f286
		summarizeBy: none
		sourceColumn: ReferralID

		annotation SummarizationSetBy = Automatic

	column CurrentStatus
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 5d8df77b-5bf6-4324-b150-ae714ce5ab41
		summarizeBy: none
		sourceColumn: CurrentStatus

		annotation SummarizationSetBy = Automatic

	column PlacementUrgencyBand
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 766596ad-a9c7-4d55-85fd-bd2a56950cc9
		summarizeBy: none
		sourceColumn: PlacementUrgencyBand

		annotation SummarizationSetBy = Automatic

	column RequiredPlacementDate
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: c1b3605c-d45b-41e7-825a-43222cf99c32
		summarizeBy: none
		sourceColumn: RequiredPlacementDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsOpen
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: f42d696a-341d-4d49-84fb-5aff960f0e90
		summarizeBy: none
		sourceColumn: IsOpen

		annotation SummarizationSetBy = Automatic

	column HasOffer
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 9ad131e5-50ac-4746-93c2-ef72fb389f3f
		summarizeBy: none
		sourceColumn: HasOffer

		annotation SummarizationSetBy = Automatic

	column OfferCount
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 95d676ce-9d08-4257-bc66-743014980ae8
		summarizeBy: sum
		sourceColumn: OfferCount

		annotation SummarizationSetBy = Automatic

	column DaysOpen
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: d975b17d-6846-4050-b054-04981743794e
		summarizeBy: sum
		sourceColumn: DaysOpen

		annotation SummarizationSetBy = Automatic

	column DaysWithoutActivity
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 91c3f0cb-2924-44c7-b0aa-17129a20a555
		summarizeBy: sum
		sourceColumn: DaysWithoutActivity

		annotation SummarizationSetBy = Automatic

	column DaysPastRequiredDate
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 225ec295-b1bd-4792-a2b6-fce4d3824087
		summarizeBy: sum
		sourceColumn: DaysPastRequiredDate

		annotation SummarizationSetBy = Automatic

	column PlacedByRequiredDate
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 40afec99-9af4-4104-82e8-0f29787eb30c
		summarizeBy: none
		sourceColumn: PlacedByRequiredDate

		annotation SummarizationSetBy = Automatic

	column RequiredPlacementDateOutcome
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: f80f2d8e-f982-49b8-8864-43cc2a3ee7a9
		summarizeBy: none
		sourceColumn: RequiredPlacementDateOutcome

		annotation SummarizationSetBy = Automatic

	column ChildID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 5b26f102-432b-42ea-a47b-07b41fa6567b
		summarizeBy: none
		sourceColumn: ChildID

		annotation SummarizationSetBy = Automatic

	column ReferralCreatedDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: f1716e27-10f6-4185-a7f1-248bd2c55712
		summarizeBy: none
		sourceColumn: ReferralCreatedDate

		annotation SummarizationSetBy = Automatic

	column FirstActionDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 2c89bc5b-1275-4fe0-adcb-bb22dba256cc
		summarizeBy: none
		sourceColumn: FirstActionDate

		annotation SummarizationSetBy = Automatic

	column FirstOfferDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: c52adb9b-a519-4dbd-845a-831d8a3ccdd7
		summarizeBy: none
		sourceColumn: FirstOfferDate

		annotation SummarizationSetBy = Automatic

	column OfferAcceptedDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: b0a374cc-8e7a-4b38-86b9-ddbe3b4da4ee
		summarizeBy: none
		sourceColumn: OfferAcceptedDate

		annotation SummarizationSetBy = Automatic

	column IPAIssuedDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: bac3b03b-1438-4ff9-9c94-993a81814a0a
		summarizeBy: none
		sourceColumn: IPAIssuedDate

		annotation SummarizationSetBy = Automatic

	column ReferralClosedDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: b8e7e10c-7de4-428c-817b-6cb9fbdbf62c
		summarizeBy: none
		sourceColumn: ReferralClosedDate

		annotation SummarizationSetBy = Automatic

	column ReferralClosureReason
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 7fd45517-cf23-402c-88f5-a0449932f598
		summarizeBy: none
		sourceColumn: ReferralClosureReason

		annotation SummarizationSetBy = Automatic

	column LastActivityDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 03dec8c9-aada-4adb-b5a0-141c7222f4f6
		summarizeBy: none
		sourceColumn: LastActivityDate

		annotation SummarizationSetBy = Automatic

	column PlacementTypeRequired
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 9df8b025-8742-416b-ba51-019aa12d0b40
		summarizeBy: none
		sourceColumn: PlacementTypeRequired

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4988426d-bc15-4a73-8f58-07b710ef07c8
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 1e981324-ae00-4037-abf5-ead3e5e6963e
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column ComplexityBand
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 52db813d-a5f9-4904-a04d-ed10d66267ed
		summarizeBy: none
		sourceColumn: ComplexityBand

		annotation SummarizationSetBy = Automatic

	column CntOfferMade
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: d7b42c61-3676-4b1e-b38d-9a1b48366594
		summarizeBy: sum
		sourceColumn: CntOfferMade

		annotation SummarizationSetBy = Automatic

	column FirstProviderSeenDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 58e79397-144c-4523-b9b3-b7b9e42013a2
		summarizeBy: none
		sourceColumn: FirstProviderSeenDate

		annotation SummarizationSetBy = Automatic

	column IsNotSeenByProviders
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 089e2acb-d140-4c06-b450-2a34a4bdb450
		summarizeBy: none
		sourceColumn: IsNotSeenByProviders

		annotation SummarizationSetBy = Automatic

	column IPAPlacementAdmissionDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 215fc319-f23b-452d-9ad8-b4e94b1f817c
		summarizeBy: none
		sourceColumn: IPAPlacementAdmissionDate

		annotation SummarizationSetBy = Automatic

	column IPA2Signatures
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 56b40e0c-a3f7-44a2-b7ef-415de1886d0b
		summarizeBy: none
		sourceColumn: IPA2Signatures

		annotation SummarizationSetBy = Automatic

	column IPALastSignatureDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 0f7e8728-9fff-479f-bbb1-8c02c168594d
		summarizeBy: none
		sourceColumn: IPALastSignatureDate

		annotation SummarizationSetBy = Automatic

	column IPADueDiligenceMinReviewDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: eb89ab66-2306-4322-8cd6-0ee43501dfac
		summarizeBy: none
		sourceColumn: IPADueDiligenceMinReviewDate

		annotation SummarizationSetBy = Automatic

	partition 'Fact Referral Snapshot' = m
		mode: directQuery
		source =
				let
				    Source = Sql.Database("m7hju2pe2lguxmyd2k56fon36e-qo2p37tm2lmuxgspbra4y6dhoa.datawarehouse.fabric.microsoft.com", "LH_BCT_WMPP"),
				    Custom1 = Source{[Schema="gold",Item="fact_referral_snapshot"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Custom1,{{"SnapshotDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
